config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tools
  # get 'home/index'
  get 'home/about'
  # root 'home#index'
  root 'tools#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :tools do
    member do
      patch 'update_date_of_use'
          end
  end

  resources :tools do
    collection do
      get 'used_tools'
    end
  end
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base # rubocop:todo Layout/EndOfLine
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/tool.rb
# app/models/tool.rb

class Tool < ApplicationRecord
	belongs_to :user
	
	# Add the attributes
	attribute :id_tool, :string
	attribute :precinto, :string
	attribute :date_of_use, :date
	attribute :date_due_to, :date
	attribute :days_left, :integer
	attribute :state, :string
	attribute :clase, :string
	attribute :pin, :string
	attribute :box, :string
	attribute :link_to_pdf, :string
	
	before_save :set_date_due_to 

	def can_update_date_of_use?
		true
	  end
	
	  def update_date_of_use(new_date)
		self.date_of_use = new_date
		set_date_due_to
		save
	  end
  
	private
  
	def set_date_due_to
	  self.date_due_to = (date_of_use + 6.months) if date_of_use.present?
	end
  end

app/models/user.rb
class User < ApplicationRecord # rubocop:todo Layout/EndOfLine
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tools

  def admin?
    admin
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base # rubocop:todo Layout/EndOfLine
	protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about
    @about_me = 'My name is Matias Aguirre.'
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: %i[show edit update destroy reset_date_of_use reset_date_of_use]
  before_action :authenticate_user!, except: %i[show index update show reset_date_of_use update_date_of_use]
 

  # GET /tools or /tools.json
  def index
    if params[:search]
      search_term = "%#{params[:search]}%"
      @tools = Tool.where("id_tool ILIKE ? OR precinto ILIKE ? OR clase ILIKE ?", search_term, search_term, search_term)
    else
      @tools = Tool.all
    end
  end

  def used_tools
    # Fetch tools that have a date of use (i.e., tools that have been used)
    @tools = Tool.where.not(date_of_use: nil)
    
    render :index  # Reuse the index view to display the filtered tools
  end


  # GET /tools/1 or /tools/1.json
  def show
  end

  # GET /tools/new
  def new
    @tool = current_user.tools.build
  end

  # GET /tools/1/edit
  def edit
  end

  # POST /tools or /tools.json
  def create
    @tool = current_user.tools.build(tool_params)

    respond_to do |format|
      if @tool.save
        format.html { redirect_to tool_url(@tool), notice: 'Tool was successfully created.' }
        format.json { render :show, status: :created, location: @tool }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tools/1 or /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to tool_url(@tool), notice: 'Tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1 or /tools/1.json
  def destroy
    @tool.destroy

    respond_to do |format|
      format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @tool = current_user.tools.find_by(id: params[:id])
    redirect_to tools_path, notice: 'Not Authorized To Edit This Tool' if @tool.nil?
  end

  def reset_date_of_use
    @tool = Tool.find(params[:id])
    @tool.update(date_of_use: nil, date_due_to: nil)

    respond_to do |format|
      format.html { redirect_to tool_url(@tool), notice: 'Date of use reset successfully.' }
      format.json { render :show, status: :ok, location: @tool }
    end
  end

  def update_date_of_use
    @tool = Tool.find(params[:id])
    if params[:reset_date_of_use]
      @tool.update(date_of_use: nil, date_due_to: nil)
      redirect_to tool_url(@tool), notice: 'Date of use reset successfully.'
    else
      if @tool.can_update_date_of_use? && @tool.update(tool_params)
        redirect_to tool_url(@tool), notice: 'Tool was successfully updated.'
      else
        # Handle update errors
      end
    end
  

  def correct_user
    @tool = Tool.find(params[:id])
    unless current_user.admin? || @tool.user == current_user
      redirect_to tools_path, notice: 'Not Authorized'
    end
  end
   

end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tool
    byebug
    @tool = Tool.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tool_params
    # Ensure date_of_use is set to nil if it's an empty string
    params.require(:tool).permit(:id_tool, :precinto, :link_to_pdf, :clase, :pin, :box , :date_of_use, :date_due_to, :days_left, :state)
          .tap { |whitelisted| whitelisted[:date_of_use] = nil if whitelisted[:date_of_use].blank? }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper # rubocop:todo Layout/EndOfLine
end

app/helpers/friends_helper.rb
module FriendsHelper # rubocop:todo Layout/EndOfLine
end

app/helpers/home_helper.rb
module HomeHelper # rubocop:todo Layout/EndOfLine
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class:"form-group">
       <%= form.text_field :first_name, class:"form-control", placeholder:"ID" %>
  </div> <br/>

  <div class:"form-group">
       <%= form.text_field :email, class:"form-control", placeholder:"Precinto" %>
  </div> <br/>

  <div class:"form-group">
        <%= form.text_field :phone, class:"form-control", placeholder:"Fecha de Uso" %>
  </div> <br/>

  <div class:"form-group">
       <%= form.text_field :twitter, class:"form-control", placeholder:"Vencimiento" %>
  </div>  <br/>

  <div class:"form-group">
       <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

<br/>
  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card h-100 text-bg-dark rounded-3">
        <div class="card-body">
          <h2 class="card-title"><%= friend.first_name %></h2>
          <h2 class="card-title"><%= friend.email %></h2>
          <p class="card-text">
            <%= friend.phone %>  |
            <%= friend.twitter %>
          </p>
          <br/>

          <!-- Link to Inspeccion -->
          <div class="mt-3">
            <%= link_to "Inspeccion", 'https://drive.google.com/file/d/17c8w4RQqzhwNHNiLA7cIuQ20YXpkqRxZ/view?usp=sharing', target: "_blank", class: "btn btn-primary" %>
          </div><br/>

      

          <% if user_signed_in? %>
            <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %>
            <%= link_to "Volver", friends_path, class:"btn btn-secondary" %>
            <br/> <br/>
            <%= button_to "Destroy", @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          <% end %>

                  </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <%= link_to root_path, class: 'navbar-brand ml-4' do %>
    <%= image_tag 'http://speservicios.com/wp-content/uploads/2020/09/logopng.png', alt: 'S.P.E. SRL Logo', class: 'img-fluid', style: 'max-width: 400px; max-height: 75px;' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Agregar', new_tool_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link text-white' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link text-white' %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/home/about.html.erb
<h1> About Us... </h1>

<p>
<%= @about_me %>
</p>

app/views/home/index.html.erb
<h1>Hello World</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Herramientas S.P.E. SRL</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
          <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tools/_form.html.erb
<%= form_with(model: tool) do |form| %>
  <% if tool.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tool.errors.count, "error") %> prohibited this tool from being saved:</h2>
      <ul>
        <% tool.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= form.text_field :clase, class: "form-control", placeholder: "Tipo de Herramienta" %>
 </div>
 <br/>

  <div class="form-group">
    <%= form.text_field :id_tool, class: "form-control", placeholder: "ID" %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.text_field :precinto, class: "form-control", placeholder: "Precinto" %>
  </div>
  <br/>

  <div class="form-group">
  <%= form.label :date_of_use, "Fecha de Uso" %>
  <%= form.date_field :date_of_use, class: "form-control", placeholder: "Fecha de Uso", value: tool.date_of_use.try(:to_date) %>
  </div>
  <br/>

  <div class="form-group">
  <%= form.text_field :pin, class: "form-control", placeholder: "Pin" %>
  </div>
  <br/>

  <div class="form-group">
  <%= form.text_field :box, class: "form-control", placeholder: "Box" %>
 </div>
 <br/>

  <div class="form-group">
    <%= form.text_field :link_to_pdf, class: "form-control", placeholder: "Link Inspeccion" %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.number_field :user_id, id: :tool_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  <br/>

  <div>
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/tools/_search.html.erb
<%= form_tag(tools_path, method: "get", class: "form-inline") do %>
	<div class="form-group mb-2">
	  <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search tools" %>
	</div>
	<%= submit_tag "Search", class: "btn btn-secondary mb-2" %>
  <% end %>
  

app/views/tools/_tool.html.erb
<div id="<%= dom_id tool %>" class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card h-100 text-bg-dark rounded-3">
        <div class="card-body">
          <h2 class="card-title text-primary"><%= tool.clase %></h2> <br/>
          <h2 class="card-title">ID: <%= tool.id_tool %></h2>
          <h2 class="card-title">Precinto: <%= tool.precinto %></h2> <br/>
          <h4 class="card-text">
            Pin: <%= tool.pin %> <br/>
            Box: <%= tool.box %> <br/> <br/>
            <div class="mt-3">

            
            <% if user_signed_in? %>
             <%= form_with(model: tool, url: tool_path(tool), method: :patch, local: true, html: { class: "update-date-form" }) do |form| %>
              <%= form.hidden_field :authenticity_token %>
             <div class="form-group">
             <%= form.label :date_of_use, "Actualizar Fecha de Uso:" %>
             <%= form.date_field :date_of_use, class: "form-control" %>
             </div> <br/>

             
             <%= form.submit "Actualizar", class: "btn btn-primary" %>
              
             <% end %>

             <div class="mt-3">
             <%= button_to "Reset", update_date_of_use_tool_path(tool), method: :patch, params: { reset_date_of_use: true }, class: "btn btn-warning" %>
           </div>
            <% end %>
             
             
             <br/>
             
            
            Fecha de Uso: <%= tool.date_of_use %> <br/>
            Fecha de Vencimiento: <%= tool.date_due_to %> <br/> 
           

          </p>
          <br/>

          <!-- Link to Inspeccion -->
          <div class="mt-1">
          <%= link_to "Inspeccion", tool.link_to_pdf, target: "_blank", class: "btn btn-success" %>
        </div><br/>

      

          <% if user_signed_in? %>
          <% if current_user.admin? || @tool.user == current_user %>
          
            <%= link_to "Edit", edit_tool_path(@tool), class:"btn btn-secondary" %> <br/> <br/>
            
            <%= button_to "Destroy", @tool, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          <% end %>
        <% end %>

          <div class="mt-3">
          <%= link_to "Volver", tools_path, class:"btn btn-primary" %>
        </div><br/>

                  </div>
      </div>
    </div>
  </div>
</div>

app/views/tools/edit.html.erb
<h1>Editing tool</h1>
<br/>

<%= render "form", tool: @tool %>


<br/>

<div>
  <%= link_to "Show", @tool, class:"btn btn-secondary" %> 
  <%= link_to "Volver", tools_path, class:"btn btn-dark" %>
</div>

app/views/tools/index.html.erb
<p style="color: green"></p>

<% if user_signed_in? %>

  <%= form_tag(tools_path, method: :get, class: "form-inline mb-3") do %>
    <div class="form-group mr-2">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search..." %>
    </div> </br>
    <%= submit_tag "Search", class: "btn btn-outline-primary " %>
  <% end %>

  <%= link_to "Show Used Tools", used_tools_tools_path, class: "btn btn-outline-success mb-3" %>

  <table class="table table-striped table-bordered table-hover mt-3">
    <thead class="table-dark">
      <tr>
        <th>ID Tool</th>
        <th>Precinto</th>
        <th>Tipo</th>
        <th>Detalles</th>
      </tr>
    </thead>

    <tbody>
      <% @tools.each do |tool| %>
        <% if tool.user == current_user %>
          <tr>
            <td>
              <%= link_to tool.id_tool, tool %>
            </td>

            <td><%= tool.precinto %></td>
            <td><%= tool.clase %></td>
            <td>
              <%= link_to 'Detalles', tool, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-info btn-sm" %>
            </td>
          </tr>
        <% end %>
      <% end %>
      
    </tbody>
  </table>

  <br>

  <%= link_to "Agregar", new_tool_path, class: "btn btn-secondary" %>

  <br/>
  <br/>

  <%= link_to "Volver", root_path, class: "btn btn-dark" %>

<% else %>

  <h1 class="mt-5 text-center">Hola! Por favor ingresar</h1>

<% end %>

app/views/tools/new.html.erb
<h1>Agregar Herramienta</h1>
<br/>

<%= render "form", tool: @tool %>

<br>

<div>
  <%= link_to "Volver", tools_path, class:"btn btn-dark" %>
</div>

app/views/tools/show.html.erb
<%= render @tool %>